// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.query.sql

package db

import (
	"context"
)

const deleteCacheItem = `-- name: DeleteCacheItem :exec
DELETE FROM cache_index
WHERE file_hash = ? AND preset = ?
`

type DeleteCacheItemParams struct {
	FileHash string
	Preset   string
}

func (q *Queries) DeleteCacheItem(ctx context.Context, arg DeleteCacheItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteCacheItem, arg.FileHash, arg.Preset)
	return err
}

const getCacheSize = `-- name: GetCacheSize :one
SELECT COALESCE(SUM(file_size), 0) FROM cache_index
`

func (q *Queries) GetCacheSize(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCacheSize)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getCached = `-- name: GetCached :one
SELECT preset_config_hash, mime_type, file_size, etag, is_stored_on_disk, data FROM cache_index
WHERE file_hash = ? AND preset = ?
`

type GetCachedParams struct {
	FileHash string
	Preset   string
}

type GetCachedRow struct {
	PresetConfigHash string
	MimeType         string
	FileSize         int64
	Etag             string
	IsStoredOnDisk   int64
	Data             []byte
}

func (q *Queries) GetCached(ctx context.Context, arg GetCachedParams) (GetCachedRow, error) {
	row := q.db.QueryRowContext(ctx, getCached, arg.FileHash, arg.Preset)
	var i GetCachedRow
	err := row.Scan(
		&i.PresetConfigHash,
		&i.MimeType,
		&i.FileSize,
		&i.Etag,
		&i.IsStoredOnDisk,
		&i.Data,
	)
	return i, err
}

const getOldestCacheItem = `-- name: GetOldestCacheItem :many
SELECT file_hash, preset, file_size, is_stored_on_disk
FROM cache_index
ORDER BY last_accessed_at ASC
LIMIT ?
`

type GetOldestCacheItemRow struct {
	FileHash       string
	Preset         string
	FileSize       int64
	IsStoredOnDisk int64
}

func (q *Queries) GetOldestCacheItem(ctx context.Context, limit int64) ([]GetOldestCacheItemRow, error) {
	rows, err := q.db.QueryContext(ctx, getOldestCacheItem, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOldestCacheItemRow
	for rows.Next() {
		var i GetOldestCacheItemRow
		if err := rows.Scan(
			&i.FileHash,
			&i.Preset,
			&i.FileSize,
			&i.IsStoredOnDisk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCache = `-- name: InsertCache :exec
INSERT INTO cache_index (file_hash, preset, preset_config_hash, data, is_stored_on_disk, mime_type, file_size, etag)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(file_hash, preset) DO UPDATE SET
    preset_config_hash = excluded.preset_config_hash,
    data = excluded.data,
    is_stored_on_disk = excluded.is_stored_on_disk,
    mime_type = excluded.mime_type,
    file_size = excluded.file_size,
    last_accessed_at = CURRENT_TIMESTAMP
`

type InsertCacheParams struct {
	FileHash         string
	Preset           string
	PresetConfigHash string
	Data             []byte
	IsStoredOnDisk   int64
	MimeType         string
	FileSize         int64
	Etag             string
}

func (q *Queries) InsertCache(ctx context.Context, arg InsertCacheParams) error {
	_, err := q.db.ExecContext(ctx, insertCache,
		arg.FileHash,
		arg.Preset,
		arg.PresetConfigHash,
		arg.Data,
		arg.IsStoredOnDisk,
		arg.MimeType,
		arg.FileSize,
		arg.Etag,
	)
	return err
}

const updateAccessTime = `-- name: UpdateAccessTime :exec
UPDATE cache_index
SET last_accessed_at = CURRENT_TIMESTAMP
WHERE file_hash = ? AND preset = ?
`

type UpdateAccessTimeParams struct {
	FileHash string
	Preset   string
}

func (q *Queries) UpdateAccessTime(ctx context.Context, arg UpdateAccessTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateAccessTime, arg.FileHash, arg.Preset)
	return err
}
