// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type CacheIndex struct {
	FileHash         string
	Preset           string
	PresetConfigHash string
	Etag             string
	MimeType         string
	FileSize         int64
	IsStoredOnDisk   int64
	CreatedAt        string
	LastAccessedAt   string
	Data             []byte
}
